name: sudo build
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.0.0
    - name: Create build environment
      run: cmake -E make_directory build
    - name: Configure
      working-directory: ${{github.workspace}}/build
      run: cmake ../ -D CMAKE_INSTALL_PREFIX=../
    - name: Build Release
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release --target install